name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        pool: 'Default'
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/luisarguero/mi_chaucherita
            azure-pipeline-name: 'mi_chaucherita-Maven-CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
